version: '3'

services:

##
#SERVIDOR NGINX COM BASE DE DADOS MYSQL
##
#  server-nginx:
#    container_name: web-server-appx
#    build: infra/web-server/nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./Project:/var/www/
#    tty: true
#    networks:
#      - appx-network
#
#  server-mysql:
#    container_name: data-base-appx
#    build: infra/data-base/mysql-5.7.22
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./.docker/dbdata:/var/lib/mysql
#    environment:
#     MYSQL_ROOT_PASSWORD: appx-laravel
#     MYSQL_DATABASE: appx-laravel
#     MYSQL_USER: appx-laravel
#     MYSQL_PASSWORD: appx-laravel
#    networks:
#     - appx-network
##
#SERVIDOR NGINX COM BASE DE DADOS MYSQL
##

##
#SERVIDOR NODE COM BASE DE DADOS MONGODB
##
  server-node:
    container_name: node-react
    build: infra/web-server/node
    tty: true
    volumes:
      - ./Project:/app
    environment:
      NODE_ENV: development
    working_dir: /app
    depends_on:
      - db-mongo
    links:
      - db-mongo
    ports:
      - '9001:3000'

  db-mongo:
    build: infra/data-base/mongo
    container_name: mongo-react
    ports:
      - '27018:27017'
    volumes:
      - ./infra/data/db:/data/db

##
#SERVIDOR NODE COM BASE DE DADOS MONGODB
##

##
#SERVIDOR MONITORAMENTO DE LOGS
##
#  server-elasticsearch:
#    container_name: elasticsearch-appx
#    build: infra/log/elasticsearch
#    ports:
#     - "9200:9200"
#    volumes:
#      - ./infra/log/elasticsearch/els-data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: single-node
#    networks:
#     - appx-network

#  server-kibana:
#    container_name: kibana-appx
#    build: infra/log/kibana
#    ports:
#      - "5601:5601"
#    networks:
#      - appx-network

#  server-logstash:
#    container_name: logstash-appx
#    build: infra/log/logstash
#    #tty: true
#    ports:
#      - "5044:5044"
#    networks:
#      - appx-network
##
#SERVIDOR MONITORAMENTO DE LOGS
##


##
#REDE USADA PARA SERVIDOR NGINX, MYSQL, ELASTIC, KIBANA E LOGSTASH
##
#networks:
#  appx-network:
#    driver: bridge
##
#REDE USADA PARA SERVIDOR NGINX, MYSQL, ELASTIC, KIBANA E LOGSTASH
##