version: '3'

services:
  server-node:
    container_name: node-react
    build: infra/web-server/node
    tty: true
    volumes:
      - ./Project:/app
    environment:
      NODE_ENV: development
    working_dir: /app
    depends_on:
      - db-mongo
    links:
      - db-mongo
    ports:
      - '9001:3000'

  db-mongo:
    build: infra/data-base/mongo
    container_name: mongo-react
    ports:
      - '27018:27017'
    volumes:
      - ./infra/data/db:/data/db